### ISSUE TITLE
Install step missing

### ISSUE THREAD

**Issue by fatmcgav** [jimmysawczuk/gpmdp#2]
The README appears to be missing a step between `go get` and `gpmdp auth`, which is to run a `go install` to compile the binary... 

Maybe it's worth producing a set of pre-compiled binaries and attaching them to Github though?

**Comment by jimmysawczuk** [comment]
Good ideas, both of them. I'll try to do that sometime soon, but feel free to create a PR if I don't beat you to it.

**Comment by fatmcgav** [comment]
I can take care of the README tweaks, but creating a release on GH is something only the repo owner can do, without additional permissions being delegated :)
